# Generated by Django 4.1.7 on 2023-04-10 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_tags_alter_entry_mod_date_entry_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('last_updated', models.DateField(default=datetime.datetime(2023, 4, 10, 11, 54, 50, 696712, tzinfo=datetime.timezone.utc))),
                ('link', models.URLField(max_length=400)),
                ('image', models.ImageField(default='image.jpg', upload_to='static/link-images/')),
                ('tag', models.ManyToManyField(blank=True, to='members.tags')),
            ],
        ),
    ]
