# Generated by Django 4.1.7 on 2023-04-10 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_usefullinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 12, 0, 1, 379810, tzinfo=datetime.timezone.utc)),
        ),
    ]
