# Generated by Django 4.1.7 on 2023-04-10 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_usefullinks_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinks',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2023, 4, 10, 13, 8, 46, 277583, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('pub_date', models.DateField()),
                ('link', models.URLField(max_length=400)),
                ('tags', models.ManyToManyField(blank=True, to='members.tags')),
            ],
        ),
    ]
