# Generated by Django 4.2.6 on 2023-10-13 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_entry_mod_date_alter_usefullinks_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateField(default=datetime.date(2023, 10, 13)),
        ),
        migrations.AlterField(
            model_name='usefullinks',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 14, 27, 49, 811391, tzinfo=datetime.timezone.utc)),
        ),
    ]
